/*************/
/* IMPORT(S) */
/*************/
import java_cup.runtime.*;
import ast.*;
import Exception.*;

parser code 
{:
	public Lexer lexer;
	
	public int errorLine;

	public Parser(Lexer lexer)
	{
		super(lexer);
		this.lexer = lexer;
	}
	public void report_error(String message, Object info)
	{
		this.errorLine = lexer.getLine();
		throw new SyntacticException(this.errorLine);
	}
:}

/************************/
/* CUSTOMIZE CUP PARSER */
/************************/
scan with
{:
	Symbol s;
	s = lexer.next_token();
	if (s.sym == TokenNames.ERROR)
	{
		throw new LexicalException();
	}

	return s;
:};


/*************/
/* TERMINALS */
/*************/
terminal IF;
terminal ELSE;
terminal EQ;
terminal DOT;
terminal PLUS;
terminal MINUS;
terminal TIMES;
terminal WHILE;
terminal DIVIDE;
terminal LPAREN;
terminal RPAREN;
terminal LBRACK;
terminal RBRACK;
terminal LBRACE;
terminal RBRACE;
terminal SEMICOLON;
terminal ASSIGN;
terminal COMMA;
terminal TYPE_INT;
terminal TYPE_STRING;
terminal TYPE_VOID;
terminal LT;
terminal GT;
terminal ARRAY;
terminal CLASS;
terminal RETURN;
terminal NEW;
terminal EXTENDS;
terminal NIL;
terminal ERROR;
/*************/
/* TERMINALS */
/*************/
terminal Integer INT;
terminal String ID;
terminal String STRING;

/*****************/
/* NON TERMINALS */
/*****************/
non terminal AstExp exp;
non terminal AstVar var;
non terminal AstStmt stmt;
non terminal AstStmtList stmtList;
non terminal AstProgram program;
non terminal AstDecList decList;
non terminal AstDec dec;
non terminal AstType type;
non terminal AstVarDec varDec;
non terminal AstFuncDec funcDec;
non terminal AstParamList paramList;
non terminal AstParam param;
non terminal AstClassDec classDec;
non terminal AstcFieldList cFieldList;
non terminal AstcField cField;
non terminal AstArrayTypeDec arrayTypedec;
non terminal AstNewExp newExp;
non terminal AstCallExp callExp;
non terminal AstExpList expList;

/***********************/
/* OPERATOR PRECEDENCE */
/***********************/
precedence nonassoc ASSIGN;
precedence left EQ;
precedence left LT;
precedence left GT;
precedence left PLUS;
precedence left MINUS;
precedence left TIMES;
precedence left DIVIDE;
precedence nonassoc LBRACK;
precedence nonassoc LPAREN;
precedence left DOT;


/************************/
/* START WITH: program */
/************************/
start with program;

/********************/
/* DERIVATION RULES */
/********************/


program		::=		decList:dl							{: RESULT = new AstProgram(dl, dl.getLine());   		:}
					;

decList		::=		dec:d decList:dl					{: RESULT = new AstDecList(d, dl, d.getLine());   	    :}
					| dec:d						     	{: RESULT = new AstDecList(d, null, d.getLine());   	:}
					;


dec			::=		varDec:vd							{: RESULT = vd;							:}
					| funcDec:fd						{: RESULT = fd;         				:}
					| classDec:cd						{: RESULT = cd;         				:}
					| arrayTypedec:atd					{: RESULT = atd;                        :}
					;

type		::=		TYPE_INT:ti							{: RESULT = new AstTypePrimitive("Int", tileft+1);           :}
					| TYPE_STRING:ts						{: RESULT = new AstTypePrimitive("String", tsleft+1);        :}
					| TYPE_VOID:tv							{: RESULT = new AstTypePrimitive("Void", tvleft+1);          :}
					| ID:id								{: RESULT = new AstTypeID(id, idleft+1);          	   	    :}
					;


varDec		::=		type:t ID:name ASSIGN exp:e SEMICOLON						{: RESULT = new AstVarDec(t, name ,e, t.getLine());				:}
					| type:t ID:name SEMICOLON									{: RESULT = new AstVarDec(t, name ,null, t.getLine());			:}
					| type:t ID:name ASSIGN newExp:ne SEMICOLON					{: RESULT = new AstVarDec(t, name ,ne, t.getLine());     		:}
					;

funcDec		::=		type:t ID:name LPAREN RPAREN LBRACE stmtList:sl RBRACE					{: RESULT = new AstFuncDec(t, name, null, sl, t.getLine());		:}
					| type:t ID:name LPAREN paramList:pl RPAREN LBRACE stmtList:sl RBRACE	{: RESULT = new AstFuncDec(t, name, pl, sl, t.getLine());		:}
					;

				
paramList   ::= 	param:p 								                             		{: RESULT = new AstParamList(p, null, p.getLine());	        	:}
					| param:p COMMA paramList:l 				                             	{: RESULT = new AstParamList(p, l, p.getLine());		         	:}
					;

param   	::=		type:t ID:name 			                                                {: RESULT = new AstParam(t, name, t.getLine());                  :}
					;

stmtList	::=		stmt:s	stmtList:l	                                                    {: RESULT = new AstStmtList(s, l, s.getLine());    	            :}
					| stmt:s			                                                    {: RESULT = new AstStmtList(s, null, s.getLine()); 	            :}
					;

classDec	::=		CLASS:c ID:name LBRACE cFieldList:l RBRACE 								{: RESULT = new AstClassDec(name, null, l, cleft+1); 		:}
					| CLASS:c ID:name1 EXTENDS ID:name2 LBRACE cFieldList:l RBRACE 			{: RESULT = new AstClassDec(name1, name2, l, cleft+1); 		:}
					;

cFieldList	::=		cField:cf	cFieldList:cfl	                                            {: RESULT = new AstcFieldList(cf, cfl, cf.getLine());            	:}
					| cField:cf			                                                    {: RESULT = new AstcFieldList(cf, null, cf.getLine()); 	        :}
					;

cField		::=		varDec:vd		{: RESULT = new AstcField(vd, vd.getLine());	        :}
					| funcDec:fd 	{: RESULT = new AstcField(fd, fd.getLine());			:}
					;

arrayTypedec::=		ARRAY:a ID:name EQ type:t LBRACK RBRACK SEMICOLON							{: RESULT = new AstArrayTypeDec(name, t, aleft+1);			:}					;

exp			::=		var:v								{: RESULT = new AstExpVarSimple(v, v.getLine());				:}
					| LPAREN exp:e RPAREN				{: RESULT = e;										 				:}
					| exp:e1 PLUS  exp:e2				{: RESULT = new AstExpBinop(e1, e2, 1, e1.getLine());			:}
					| exp:e1 MINUS exp:e2				{: RESULT = new AstExpBinop(e1, e2, 2, e1.getLine());			:}
					| exp:e1 TIMES exp:e2				{: RESULT = new AstExpBinop(e1, e2, 3, e1.getLine());			:}
					| exp:e1 DIVIDE exp:e2				{: RESULT = new AstExpBinop(e1, e2, 4, e1.getLine());			:}
					| exp:e1 LT exp:e2					{: RESULT = new AstExpBinop(e1, e2, 5, e1.getLine());			:}
					| exp:e1 GT exp:e2					{: RESULT = new AstExpBinop(e1, e2, 6, e1.getLine());			:}
					| exp:e1 EQ exp:e2					{: RESULT = new AstExpBinop(e1, e2, 7, e1.getLine());			:}
					| callExp:ce						{: RESULT = ce;  							   					:}
					| MINUS:m INT:i						{: RESULT = new AstExpInt(-i, mleft+1);          				:}
					| INT:i								{: RESULT = new AstExpInt(i, ileft+1);          		:}
					| NIL:n								{: RESULT = new AstExpNil(nleft+1);          			:}
					| STRING:s							{: RESULT = new AstExpString(s, sleft+1);          		:}
					;

newExp		::=		NEW type:t									{: RESULT = new AstNewExpSimple(t, t.getLine());					:}
					| NEW type:t LBRACK exp:e RBRACK			{: RESULT =	new AstNewExpArr(t, e, t.getLine());							:}
					;

callExp		::= 	var:v DOT ID:name LPAREN expList:l RPAREN		{: RESULT = new AstCallExp(v, name, l, v.getLine());					:}
					| var:v DOT ID:name LPAREN RPAREN				{: RESULT = new AstCallExp(v, name, null, v.getLine());					:}
					| ID:name LPAREN expList:l RPAREN				{: RESULT = new AstCallExp(null, name, l, l.getLine());				:}
					| ID:name LPAREN RPAREN							{: RESULT = new AstCallExp(null, name, null,  nameleft+1);				:}
					;

expList		::=		exp:e COMMA expList:l						{: RESULT = new AstExpList(e, l, e.getLine()); 			     :}
					| exp:e										{: RESULT = new AstExpList(e, null, e.getLine()); 		:}
					;

var			::=		ID:name										{: RESULT = new AstVarSimple(name, nameleft+1);               	  :}
					| var:v DOT ID:fieldName					{: RESULT = new AstVarField(v, fieldName, v.getLine()); 	          :}
					| var:v LBRACK exp:e RBRACK					{: RESULT = new AstVarSubscript(v, e, v.getLine());      			  :}
					;
					
stmt		::=		varDec:v																								{: RESULT = new AstStmtVarDec(v, v.getLine());					:} 
					| var:v ASSIGN exp:e SEMICOLON																			{: RESULT = new AstStmtAssign(v, e, v.getLine()); 				:}
					| var:v ASSIGN newExp:ne SEMICOLON																		{: RESULT = new AstStmtAssign(v, ne, v.getLine()); 				:}
					| RETURN SEMICOLON																						{: RESULT = new AstStmtReturn(null, lexer.getLine()); 			:} 
					| RETURN exp:e SEMICOLON																				{: RESULT = new AstStmtReturn(e, e.getLine()); 					:}
					| IF LPAREN exp:cond RPAREN LBRACE stmtList:body RBRACE													{: RESULT = new AstStmtIf(cond, body, cond.getLine()); 			:} 
					| IF LPAREN exp:cond RPAREN LBRACE stmtList:body RBRACE ELSE LBRACE stmtList:elsebody RBRACE			{: RESULT = new AstStmtIf(cond, body, elsebody, cond.getLine());:}
					| WHILE LPAREN exp:cond RPAREN LBRACE stmtList:body RBRACE												{: RESULT = new AstStmtWhile(cond, body, cond.getLine()); 		:}
					| callExp:ce SEMICOLON																					{: RESULT = new AstStmtCall(ce, ce.getLine());					:}
					;

