/*************/
/* IMPORT(S) */
/*************/
import java_cup.runtime.*;
import ast.*;

parser code 
{:
	public Lexer lexer;
	
	public int errorLine;

	public Parser(Lexer lexer)
	{
		super(lexer);
		this.lexer = lexer;
	}
	public void report_error(String message, Object info)
	{
		this.errorLine = lexer.getLine();
		throw new RuntimeException("syntax error");
	}
:}

/************************/
/* CUSTOMIZE CUP PARSER */
/************************/
scan with
{:
	Symbol s;
	s = lexer.next_token();
	if (s.sym == TokenNames.ERROR)
	{
		throw new RuntimeException("lex error");
	}

	return s;
:};

/*************/
/* TERMINALS */
/*************/
terminal IF;
terminal ELSE;
terminal EQ;
terminal DOT;
terminal PLUS;
terminal MINUS;
terminal TIMES;
terminal WHILE;
terminal DIVIDE;
terminal LPAREN;
terminal RPAREN;
terminal LBRACK;
terminal RBRACK;
terminal LBRACE;
terminal RBRACE;
terminal SEMICOLON;
terminal ASSIGN;
terminal COMMA;
terminal TYPE_INT;
terminal TYPE_STRING;
terminal TYPE_VOID;
terminal LT;
terminal GT;
terminal ARRAY;
terminal CLASS;
terminal RETURN;
terminal NEW;
terminal EXTENDS;
terminal NIL;
terminal ERROR;
/*************/
/* TERMINALS */
/*************/
terminal Integer INT;
terminal String ID;
terminal String STRING;

/*****************/
/* NON TERMINALS */
/*****************/
non terminal AstExp exp;
non terminal AstVar var;
non terminal AstStmt stmt;
non terminal AstStmtList stmtList;
non terminal AstProgram program;
non terminal AstDecList decList;
non terminal AstDec dec;
non terminal AstTypePrimitive type;
non terminal AstTypeID typeID;
non terminal AstVarDec varDec;
non terminal AstFuncDec funcDec;
non terminal AstParamList paramList;
non terminal AstParam param;
non terminal AstClassDec classDec;
non terminal AstcFieldList cFieldList;
non terminal AstcField cField;
non terminal AstArrayTypeDec arrayTypedef;
non terminal AstNewExp newExp;
non terminal AstCallExp callExp;
non terminal AstExpList expList;

/***********************/
/* OPERATOR PRECEDENCE */
/***********************/
precedence nonassoc ASSIGN;
precedence left EQ;
precedence left LT;
precedence left GT;
precedence left PLUS;
precedence left MINUS;
precedence left TIMES;
precedence left DIVIDE;
precedence nonassoc LBRACK;
precedence nonassoc LPAREN;
precedence left DOT;


/************************/
/* START WITH: program */
/************************/
start with program;

/********************/
/* DERIVATION RULES */
/********************/


program		::=		decList:dl							{: RESULT = new AstProgram(dl);   		:}
					;

decList		::=		dec:d decList:dl					{: RESULT = new AstDecList(d, dl);   	:}
					| dec:d						     	{: RESULT = new AstDecList(d, null); 	:}
					;


dec			::=		varDec:vd							{: RESULT = vd;							:}
					| funcDec:fd						{: RESULT = fd;         				:}
					| classDec:cd						{: RESULT = cd;         				:}
					| arrayTypedef:atd					{: RESULT = atd;                        :}
					;

type		::=		TYPE_INT							{: RESULT = new AstTypePrimitive("Int");           :}
					| TYPE_STRING						{: RESULT = new AstTypePrimitive("String");        :}
					| TYPE_VOID							{: RESULT = new AstTypePrimitive("Void");          :}
					| ID:id								{: RESULT = new AstTypeID(id);          		   :}
					;


varDec		::=		type:t ID:name ASSIGN exp:e SEMICOLON						{: RESULT = new AstVarDec(t, name ,e);				:}
					| type:t ID:name SEMICOLON									{: RESULT = new AstVarDec(t, name ,null);			:}
					| type:t ID:name ASSIGN newExp:ne SEMICOLON					{: RESULT = new AstVarDec(t, name ,ne);     		:}
					;

funcDec		::=		type:t ID:name LPAREN RPAREN LBRACE stmtList:sl RBRACE					{: RESULT = new AstFuncDec(t, name, null, sl);		:}
					| type:t ID:name LPAREN paramList:pl RPAREN LBRACE stmtList:sl RBRACE	{: RESULT = new AstFuncDec(t, name, pl, sl);		:}
					;

				
paramList   ::= 	param:p 								                             		{: RESULT = new AstParamList(p, null);	        	:}
					| param:p COMMA paramList:l 				                             	{: RESULT = new AstParamList(p, l);		         	:}
					;

param   	::=		type:t ID:name 			                                                {: RESULT = new AstParam(t, name);                  :}
					;

stmtList	::=		stmt:s	stmtList:l	                                                    {: RESULT = new AstStmtList(s, l);    	            :}
					| stmt:s			                                                    {: RESULT = new AstStmtList(s, null); 	            :}
					;

classDec	::=		CLASS ID:name LBRACE cFieldList:l RBRACE 								{: RESULT = new AstClassDec(name, null, l); 		:}
					| CLASS ID:name1 EXTENDS ID:name2 LBRACE cFieldList:l RBRACE 			{: RESULT = new AstClassDec(name1, name2, l); 		:}
					;

cFieldList	::=		cField:cf	cFieldList:cfl	                                            {: RESULT = new AstcFieldList(cf, cfl);            	:}
					| cField:cf			                                                    {: RESULT = new AstcFieldList(cf, null); 	        :}
					;

cField		::=		varDec:vd		{: RESULT = new AstcField(vd);	        :}
					| funcDec:fd 	{: RESULT = new AstcField(fd);			:}
					;

arrayTypedef::=		ARRAY ID:name EQ type:t LBRACK RBRACK SEMICOLON							{: RESULT = new AstArrayTypeDec(name, t);			:}
					;

exp			::=		var:v								{: RESULT = new AstExpVar(v);					:}
					| LPAREN exp:e RPAREN				{: RESULT = e;					 				:}
					| exp:e1 PLUS  exp:e2				{: RESULT = new AstExpBinop(e1, e2, 0);			:}
					| exp:e1 MINUS exp:e2				{: RESULT = new AstExpBinop(e1, e2, 1);			:}
					| exp:e1 TIMES exp:e2				{: RESULT = new AstExpBinop(e1, e2, 2);			:}
					| exp:e1 DIVIDE exp:e2				{: RESULT = new AstExpBinop(e1, e2, 3);			:}
					| exp:e1 LT exp:e2					{: RESULT = new AstExpBinop(e1, e2, 4);			:}
					| exp:e1 GT exp:e2					{: RESULT = new AstExpBinop(e1, e2, 5);			:}
					| exp:e1 EQ exp:e2					{: RESULT = new AstExpBinop(e1, e2, 6);			:}
					| callExp:ce						{: RESULT = ce;  							   	:}
					| MINUS INT:i						{: RESULT = new AstExpInt(-i);          		:}
					| INT:i								{: RESULT = new AstExpInt(i);          			:}
					| NIL								{: RESULT = new AstExpNil();          			:}
					| STRING:s							{: RESULT = new AstExpString(s);          		:}
					;

newExp		::=		NEW type:t									{: RESULT = new AstNewExpSimple(t);					:}
					| NEW type:t LBRACK exp:e RBRACK			{: RESULT =	new AstNewExpArr(t, e);							:}
					;

callExp		::= 	var:v DOT ID:name LPAREN expList:l RPAREN		{: RESULT = new AstCallExp(v, name, l);					:}
					| var:v DOT ID:name LPAREN RPAREN				{: RESULT = new AstCallExp(v, name, null);					:}
					| ID:name LPAREN expList:l RPAREN				{: RESULT = new AstCallExp(null, name, l);				:}
					| ID:name LPAREN RPAREN							{: RESULT = new AstCallExp(null, name, null);				:}
					;

expList		::=		exp:e COMMA expList:l						{: RESULT = new AstExpList(e, l); 			     :}
					| exp:e										{: RESULT = new AstExpList(e, null); 		:}
					;

var			::=		ID:name										{: RESULT = new AstVarSimple(name);       	:}
					| var:v DOT ID:fieldName					{: RESULT = new AstVarField(v, fieldName); 	          :}
					| var:v LBRACK exp:e RBRACK					{: RESULT = new AstVarSubscript(v, e);        	:}
					;
					
stmt		::=		varDec:v																								{: RESULT = new AstStmtVarDec(v);				:} 
					| var:v ASSIGN exp:e SEMICOLON																			{: RESULT = new AstStmtAssign(v, e); 			:}
					| var:v ASSIGN newExp:ne SEMICOLON																		{: RESULT = new AstStmtAssign(v, ne); 			:}
					| RETURN SEMICOLON																						{: RESULT = new AstStmtReturn(null); 			:} 
					| RETURN exp:e SEMICOLON																				{: RESULT = new AstStmtReturn(e); 				:}
					| IF LPAREN exp:cond RPAREN LBRACE stmtList:body RBRACE													{: RESULT = new AstStmtIf(cond, body); 			:} 
					| IF LPAREN exp:cond RPAREN LBRACE stmtList:body RBRACE ELSE LBRACE stmtList:elsebody RBRACE			{: RESULT = new AstStmtIf(cond, body, elsebody);:}
					| WHILE LPAREN exp:cond RPAREN LBRACE stmtList:body RBRACE												{: RESULT = new AstStmtWhile(cond, body); 		:}
					| callExp:ce SEMICOLON																					{: RESULT = new AstStmtCall(ce);				:}
					;

